# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a073e4ad0a075dc59a2281975f9d65aab95e7b76c0ef96ebef24e31a8770a456f1b5edd4a0f294fd52648f3f866b8d9ed01851d10866137716484c0975a3f9a

test:
  secret_key_base: 5716497fb9f01ee834bb78e4c2caf1d71b9a09fb7d1f89f041f1a9973b364955eed1735107a4c8c4f3bebe3efd850e01626707d88f70afaa58b751063149f72e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
